document.addEventListener('DOMContentLoaded', function() {
        // Mobile menu toggle
            const hamburger = document.querySelector('.hamburger');
                const navLinks = document.querySelector('.nav-links');
                    const navItems = document.querySelectorAll('.nav-links li');

                        hamburger.addEventListener('click', () => {
                                navLinks.classList.toggle('active');
                                        hamburger.classList.toggle('active');
                                            });

                                                // Close mobile menu when clicking on a link
                                                    navItems.forEach(item => {
                                                            item.addEventListener('click', () => {
                                                                        navLinks.classList.remove('active');
                                                                                    hamburger.classList.remove('active');
                                                                                            });
                                                                                                });

                                                                                                    // Smooth scrolling for anchor links
                                                                                                        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
                                                                                                                anchor.addEventListener('click', function(e) {
                                                                                                                            e.preventDefault();
                                                                                                                                        
                                                                                                                                                    const targetId = this.getAttribute('href');
                                                                                                                                                                const targetElement = document.querySelector(targetId);
                                                                                                                                                                            
                                                                                                                                                                                        if (targetElement) {
                                                                                                                                                                                                        window.scrollTo({
                                                                                                                                                                                                                            top: targetElement.offsetTop - 80,
                                                                                                                                                                                                                                                behavior: 'smooth'
                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                            // Sticky header on scroll
                                                                                                                                                                                                                                                                                                const header = document.querySelector('header');
                                                                                                                                                                                                                                                                                                    window.addEventListener('scroll', () => {
                                                                                                                                                                                                                                                                                                            if (window.scrollY > 100) {
                                                                                                                                                                                                                                                                                                                        header.style.background = 'rgba(44, 62, 80, 0.95)';
                                                                                                                                                                                                                                                                                                                                    header.style.padding = '15px 0';
                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                        header.style.background = 'var(--secondary-color)';
                                                                                                                                                                                                                                                                                                                                                                    header.style.padding = '20px 0';
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                    // Animate skill bars on scroll
                                                                                                                                                                                                                                                                                                                                                                                        const skillBars = document.querySelectorAll('.skill-level');
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                function animateSkillBars() {
                                                                                                                                                                                                                                                                                                                                                                                                        skillBars.forEach(bar => {
                                                                                                                                                                                                                                                                                                                                                                                                                    const width = bar.style.width;
                                                                                                                                                                                                                                                                                                                                                                                                                                bar.style.width = '0';
                                                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            bar.style.width = width;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Intersection Observer for skill bars animation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const skillsSection = document.querySelector('.skills');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const observer = new IntersectionObserver((entries) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        entries.forEach(entry => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (entry.isIntersecting) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animateSkillBars();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    observer.unobserve(entry.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, { threshold: 0.5 });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (skillsSection) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        observer.observe(skillsSection);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Form submission
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const contactForm = document.querySelector('.contact-form form');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (contactForm) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                contactForm.addEventListener('submit', function(e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert('Thank you for your message! I will get back to you soon.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.reset();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
})